### ISSUE TITLE
Make hints lightbulb button more obvious

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#273]
Some users don't notice it at all

**Comment by spamegg1** [comment]
I offer 8 options:
1. No change:
![0](https://user-images.githubusercontent.com/4255997/149667080-77849f3f-5c60-4a54-a810-41c74af82d59.png)

1. Simply make the icon larger:
```scss
// main.scss
.hint-icon {
  position: fixed;
  bottom: 10%;
  right: 10px;
  //width: 48px;
  width: 72px;
  //height: 48px;
  height: 72px;
}
```
![1](https://user-images.githubusercontent.com/4255997/149667093-f98b67bd-d924-4b0c-af0a-2832dec534a5.png)

2. Make it animated (same size). It blinks between white/red background once per second:
```js
// Hints.js
//import hintIcon from "./img/hint.png";
import hintIcon from "./img/hint.gif";
```
![2](https://user-images.githubusercontent.com/4255997/149667220-965ee1be-00f4-4035-a474-c688351f2325.png)

3. Make it animated, AND larger:
![3](https://user-images.githubusercontent.com/4255997/149667326-f2ba5402-cbfe-411f-bf58-b06550cb9657.png)

Then: basically the same as 0,1,2,3 but, in the middle of the screen, and slightly more elevated from the bottom:
```scss
// main.scss
.hint-icon {
  position: fixed;
  //bottom: 10px;
  bottom: 10%;
  //right: 10px;
  right: 50%;
  width: 48px;
  height: 48px;
}
```
4.
![4](https://user-images.githubusercontent.com/4255997/149667552-e6366fb9-6e80-4498-bc13-7a8976151e5d.png)

5.
![5](https://user-images.githubusercontent.com/4255997/149667557-271b9613-fe09-45f6-9b10-6b8e5db5e146.png)

6.
![6](https://user-images.githubusercontent.com/4255997/149667568-c5992830-8e0d-479b-8edb-8169fb6e8077.png)

7.
![7](https://user-images.githubusercontent.com/4255997/149667584-3054bcae-6873-4849-853d-35a4071ae409.png)

Or something else... (beyond my ability)
